# safelist
branches:
  only:
  - master

os:
  - linux
  - osx

sudo: false

language: c

before_install:
   - sudo apt-get -qq update
   - sudo apt-get install gcc-5

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update > /dev/null; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew reinstall libtool > /dev/null; fi

before_script:
  - wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz -O /tmp/autoconf-2.69.tar.gz
  - pushd /tmp && tar -xvzf autoconf-2.69.tar.gz && cd autoconf-2.69 && ./configure --prefix=/tmp/mine && make && make install && popd

script: export PATH=/tmp/mine/bin:$PATH; sh ./autogen.sh && ./configure && make && make check

compiler:
  - gcc

notifications:
email: true

