# .travis.yml --
#
# Travis CI configuration for CCExceptions.

# About compiler  packages.  We  select build by  build the  packages to
# install; it should speed up preparation.  By putting a single "addons"
# key at the top level: we would cause all the compilers to be installed
# for all the builds in the matrix; we do not want this.

# About compiler  selection.  We  select the compiler  we want  with the
# "compiler" key.   This should set  the environment variable CC  to the
# associated compiler executable; I have  verified that it actually does
# so when  the language is C.   I am not  sure that it actually  does it
# when the language is C++.  (Marco Maggi; May 27, 2017)

# About  dependency  packages.   We install  dependency  packages  under
# "/tmp/mine".   So we  need the  following in  every script  that needs
# custom dependencies:
#
#   export PATH=/tmp/mine/bin:$PATH;
#   export LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
#   export PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
#
# otherwise the installed packages will not be found and used correctly.

sudo: false
language: c

# Let's just look at the project's dashboard at Travis CI's site.
#
notifications:
  email: false

# We do no git operations, so set this to the minimum.
#
git:
  depth: 1

branches:
  only:
    - master

env:
  global:
    - MAKEFLAGS="-j 2"
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "GCyS6Y0E3uYWr5pTgQkVlMorDmEU0b4YvBvqQBjFWZkNlswJBbX0fAB2pFIMHveWtTCihGJBW5pvVeBMDM2YqE3MgVavGmg9kYqp1S3scx+LygqXS7a05cRerpcClJ23vsNAxxr8kHTVyn0LyiFtn6ulWghH3HvvBUNXf7QDVeDn9Otz2k5dE2asLvwvhYFyrBJfYQaGOVaJHgnKQ3XuXYEMKlm4NJTC3UjEdlssElcncicDdtOI1Zv08pHUTrKn0fODOcjscSvSm6382mkqEuDVVNoD0XJuaQJmjSFuae5ggWdcGxDacrA66WSjJ2fc21ns6L9o+OKVj88xPES9TBNS96mB0pJT05BaPDDAjFpunHIOl6oBQu19UfOi9nWB9IDzygUNcPcOF9AIAKoOpUr+3jhodzt7/esDHmPv6LGWdPqZODzZVR1y+t/10dVoVceKUhZUwHnoJgaiRz1btCHCwcLbWhYlq+kncoIKjYpgounsgEHYAIiYtYsPpdH2PSyrj66uPXcur3dXKfjHywK14R5cJKEbTjNsB4FEghedr6lpq3tD1HhS9wXClQi54zfxeLSBmIEJVxN9cB2DBYrEzF8/a51b2G8VBythtcPl7qWRHZEUQQQyv9DCMQ1thQqbVeQfSgg/XVgk8yFGdR4320qYbt9gnl5LU/Cf/Nc="

matrix:
  #allow_failures:
  #  - os: linux
  #    compiler: clang

  fast_finish: true

  include:
    # Plain build under Ubuntu GNU+Linux "trusty", GCC 5.
    - os: linux
      dist: trusty
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-5
      script: |
        #echo CC=$CC; $CC --version;
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode;
        make all;
        make check;

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 6.
    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-6
      script: |
        #echo CC=$CC; $CC --version;
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode;
        make all;
        make check;

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 7.
    - os: linux
      dist: trusty
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-7
      script: |
        #echo CC=$CC; $CC --version;
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode;
        make all;
        make check;

    # Plain build  under Ubuntu GNU+Linux "trusty",  CLang automatically
    # selected by Travis CI.
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
      compiler: clang
      script: |
        #echo CC=$CC; $CC --version;
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode CFLAGS='-Wno-unknown-attributes';
        make all;
        make check;

    # Plain build under OS X, XCode 7.3, CLang automatically selected by
    # Travis CI.
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      script: |
        #echo CC=$CC; $CC --version;
        LIBTOOLIZE=glibtoolize sh ./autogen.sh;
        ./configure --enable-maintainer-mode CFLAGS='-Wno-unknown-attributes';
        make all;
        (RV=0; if ! make check ; then RV=$?; cat test-suite.log ; fi; exit $RV;)

    # Plain build under OS X, XCode 8.3, CLang automatically selected by
    # Travis CI.
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      script: |
        #echo CC=$CC; $CC --version;
        LIBTOOLIZE=glibtoolize sh ./autogen.sh;
        ./configure --enable-maintainer-mode CFLAGS='-Wno-unknown-attributes';
        make all;
        (RV=0; if ! make check ; then RV=$?; cat test-suite.log ; fi; exit $RV;)

    # Codecov support under Ubuntu GNU+Linux "trusty", GCC 7.
    - os: linux
      dist: trusty
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-7
      script: |
        #echo CC=$CC; $CC --version;
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode CFLAGS='-O0 --coverage';
        make all;
        make check;
      after_success:
        bash <(curl -s https://codecov.io/bash) -xgcov-7

    # Coverity Scan support under Ubuntu GNU+Linux "trusty", GCC 7.
    - os: linux
      dist: trusty
      compiler: gcc-7
      branches:
        only:
          - coverity_scan
      before_install:
            - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-7
        coverity_scan:
          project:
            name: "marcomaggi/ccexceptions"
            description: "Build submitted via Travis CI"
          notification_email: marco.maggi-ipsu@poste.it
          build_command_prepend: |
            sh ./autogen.sh;
            ./configure --enable-maintainer-mode;
            make clean
          build_command: "make all"
          branch_pattern: coverity_scan
      script: |
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode;
        make all;
        make check;

### end of file
