# safelist
branches:
  only:
  - master

os:
  - linux
  - osx

sudo: false

language: c

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update > /dev/null; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew reinstall libtool > /dev/null; fi

before_script:
  - wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz -O /tmp/autoconf-2.69.tar.gz
  - cd /tmp && tar -xvzf autoconf-2.69.tar.gz && cd autoconf-2.69 && ./configure && make && make install
  - sh ./autogen.sh

script: ./configure && make && make check

compiler:
  - gcc

notifications:
email: true

