/*
  Part of: CCExceptions
  Contents: exceptional condition descriptor functions
  Date: Dec 26, 2016

  Abstract



  Copyright (C) 2016 Marco Maggi <marco.maggi-ipsu@poste.it>

  This is free software; you  can redistribute it and/or modify it under
  the terms of the GNU Lesser General Public License as published by the
  Free Software  Foundation; either version  3.0 of the License,  or (at
  your option) any later version.

  This library  is distributed in the  hope that it will  be useful, but
  WITHOUT   ANY  WARRANTY;   without  even   the  implied   warranty  of
  MERCHANTABILITY  or FITNESS  FOR A  PARTICULAR PURPOSE.   See  the GNU
  Lesser General Public License for more details.

  You  should have  received a  copy of  the GNU  Lesser  General Public
  License along  with this library; if  not, write to  the Free Software
  Foundation, Inc.,  59 Temple Place,  Suite 330, Boston,  MA 02111-1307
  USA.

*/


#include "ccexceptions-internals.h"
#include <limits.h>	// for INT_MAX
#include <errno.h>
#include <string.h>	// for strerror()

void
cce_condition_free (void * _condition)
{
  cce_condition_t *	C = _condition;
  if (C->table->free) {
    C->table->free(C);
  }
}
const char *
cce_condition_static_message (void * _condition)
{
  cce_condition_t *	C = _condition;
  return C->table->static_message(C);
}


typedef struct cce_errno_condition_t {
  cce_condition_functions_table_t *	table;
  int					errnum;
  const char *				message;
} cce_errno_condition_t;

static const char * cce_condition_errno_static_message_fun (void * _condition) {
  cce_errno_condition_t	* C = _condition;
  return C->message;
}

static cce_condition_functions_table_t cce_condition_errno_table = {
  NULL, // cce_condition_free_fun_t *
  cce_condition_errno_static_message_fun
};

#define CCE_DECLARE_ERRNO_CONDITION(ERRNO,MESSAGE)	\
  							\
  {							\
    .table	= &cce_condition_errno_table,		\
    .errnum	= ERRNO,				\
    .message	= MESSAGE				\
  }

static const cce_errno_condition_t
cce_errno_conditions[] = {
  CCE_DECLARE_ERRNO_CONDITION(0,			"(errno=0) Success"),
  /* Whenever  an  errno  constant  is not  defined  by  the  underlying
     platform:  the  "configure"  script  defines it  as  -1.   Here  we
     intercept the -1 value so that  it is not mistaken for an undefined
     constant. */
  CCE_DECLARE_ERRNO_CONDITION(-1,			"Invalid errno value"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EPERM,		"(errno=EPERM)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOENT,		"(errno=ENOENT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ESRCH,		"(errno=ESRCH)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EINTR,		"(errno=EINTR)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EIO,		"(errno=EIO)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENXIO,		"(errno=ENXIO)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_E2BIG,		"(errno=E2BIG)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOEXEC,		"(errno=ENOEXEC)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EBADF,		"(errno=EBADF)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ECHILD,		"(errno=ECHILD)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EAGAIN,		"(errno=EAGAIN)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOMEM,		"(errno=ENOMEM)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EACCES,		"(errno=EACCES)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EFAULT,		"(errno=EFAULT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOTBLK,		"(errno=ENOTBLK)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EBUSY,		"(errno=EBUSY)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EEXIST,		"(errno=EEXIST)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EXDEV,		"(errno=EXDEV)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENODEV,		"(errno=ENODEV)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOTDIR,		"(errno=ENOTDIR)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EISDIR,		"(errno=EISDIR)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EINVAL,		"(errno=EINVAL) Invalid argument"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENFILE,		"(errno=ENFILE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EMFILE,		"(errno=EMFILE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOTTY,		"(errno=ENOTTY)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ETXTBSY,		"(errno=ETXTBSY)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EFBIG,		"(errno=EFBIG)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOSPC,		"(errno=ENOSPC)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ESPIPE,		"(errno=ESPIPE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EROFS,		"(errno=EROFS)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EMLINK,		"(errno=EMLINK)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EPIPE,		"(errno=EPIPE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EDOM,		"(errno=EDOM)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ERANGE,		"(errno=ERANGE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EDEADLK,		"(errno=EDEADLK)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENAMETOOLONG,	"(errno=ENAMETOOLONG)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOLCK,		"(errno=ENOLCK)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOSYS,		"(errno=ENOSYS)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOTEMPTY,	"(errno=ENOTEMPTY)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ELOOP,		"(errno=ELOOP)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EWOULDBLOCK,	"(errno=EWOULDBLOCK)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOMSG,		"(errno=ENOMSG)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EIDRM,		"(errno=EIDRM)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ECHRNG,		"(errno=ECHRNG)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EL2NSYNC,		"(errno=EL2NSYNC)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EL3HLT,		"(errno=EL3HLT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EL3RST,		"(errno=EL3RST)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ELNRNG,		"(errno=ELNRNG)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EUNATCH,		"(errno=EUNATCH)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOCSI,		"(errno=ENOCSI)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EL2HLT,		"(errno=EL2HLT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EBADE,		"(errno=EBADE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EBADR,		"(errno=EBADR)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EXFULL,		"(errno=EXFULL)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOANO,		"(errno=ENOANO)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EBADRQC,		"(errno=EBADRQC)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EBADSLT,		"(errno=EBADSLT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EDEADLOCK,	"(errno=EDEADLOCK)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EBFONT,		"(errno=EBFONT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOSTR,		"(errno=ENOSTR)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENODATA,		"(errno=ENODATA)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ETIME,		"(errno=ETIME)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOSR,		"(errno=ENOSR)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENONET,		"(errno=ENONET)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOPKG,		"(errno=ENOPKG)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EREMOTE,		"(errno=EREMOTE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOLINK,		"(errno=ENOLINK)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EADV,		"(errno=EADV)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ESRMNT,		"(errno=ESRMNT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ECOMM,		"(errno=ECOMM)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EPROTO,		"(errno=EPROTO)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EMULTIHOP,	"(errno=EMULTIHOP)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EDOTDOT,		"(errno=EDOTDOT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EBADMSG,		"(errno=EBADMSG)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EOVERFLOW,	"(errno=EOVERFLOW)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOTUNIQ,		"(errno=ENOTUNIQ)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EBADFD,		"(errno=EBADFD)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EREMCHG,		"(errno=EREMCHG)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ELIBACC,		"(errno=ELIBACC)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ELIBBAD,		"(errno=ELIBBAD)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ELIBSCN,		"(errno=ELIBSCN)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ELIBMAX,		"(errno=ELIBMAX)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ELIBEXEC,		"(errno=ELIBEXEC)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EILSEQ,		"(errno=EILSEQ)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ERESTART,		"(errno=ERESTART)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ESTRPIPE,		"(errno=ESTRPIPE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EUSERS,		"(errno=EUSERS)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOTSOCK,		"(errno=ENOTSOCK)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EDESTADDRREQ,	"(errno=EDESTADDRREQ)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EMSGSIZE,		"(errno=EMSGSIZE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EPROTOTYPE,	"(errno=EPROTOTYPE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOPROTOOPT,	"(errno=ENOPROTOOPT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EPROTONOSUPPORT,	"(errno=EPROTONOSUPPORT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ESOCKTNOSUPPORT,	"(errno=ESOCKTNOSUPPORT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EOPNOTSUPP,	"(errno=EOPNOTSUPP)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EPFNOSUPPORT,	"(errno=EPFNOSUPPORT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EAFNOSUPPORT,	"(errno=EAFNOSUPPORT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EADDRINUSE,	"(errno=EADDRINUSE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EADDRNOTAVAIL,	"(errno=EADDRNOTAVAIL)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENETDOWN,		"(errno=ENETDOWN)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENETUNREACH,	"(errno=ENETUNREACH)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENETRESET,	"(errno=ENETRESET)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ECONNABORTED,	"(errno=ECONNABORTED)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ECONNRESET,	"(errno=ECONNRESET)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOBUFS,		"(errno=ENOBUFS)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EISCONN,		"(errno=EISCONN)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOTCONN,		"(errno=ENOTCONN)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ESHUTDOWN,	"(errno=ESHUTDOWN)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ETOOMANYREFS,	"(errno=ETOOMANYREFS)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ETIMEDOUT,	"(errno=ETIMEDOUT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ECONNREFUSED,	"(errno=ECONNREFUSED)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EHOSTDOWN,	"(errno=EHOSTDOWN)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EHOSTUNREACH,	"(errno=EHOSTUNREACH)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EALREADY,		"(errno=EALREADY)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EINPROGRESS,	"(errno=EINPROGRESS)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ESTALE,		"(errno=ESTALE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EUCLEAN,		"(errno=EUCLEAN)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOTNAM,		"(errno=ENOTNAM)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENAVAIL,		"(errno=ENAVAIL)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EISNAM,		"(errno=EISNAM)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EREMOTEIO,	"(errno=EREMOTEIO)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EDQUOT,		"(errno=EDQUOT)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOMEDIUM,	"(errno=ENOMEDIUM)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EMEDIUMTYPE,	"(errno=EMEDIUMTYPE)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ECANCELED,	"(errno=ECANCELED)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOKEY,		"(errno=ENOKEY)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EKEYEXPIRED,	"(errno=EKEYEXPIRED)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EKEYREVOKED,	"(errno=EKEYREVOKED)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EKEYREJECTED,	"(errno=EKEYREJECTED)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_EOWNERDEAD,	"(errno=EOWNERDEAD)"),
  CCE_DECLARE_ERRNO_CONDITION(VALUEOF_ENOTRECOVERABLE,	"(errno=ENOTRECOVERABLE)"),
  CCE_DECLARE_ERRNO_CONDITION(INT_MAX,			"Unknown errno code")
};

static const cce_errno_condition_t cce_invalid_errno_condition = CCE_DECLARE_ERRNO_CONDITION(INT_MAX, "Unknown errno code");

cce_condition_t *
cce_condition_errno (int errnum)
{
  for (int i = 0; INT_MAX != cce_errno_conditions[i].errnum; ++i) {
    if (errnum == cce_errno_conditions[i].errnum) {
      return (cce_condition_t *) &(cce_errno_conditions[i]);
    }
  }
  /* If  we  are  here  ERRNUM  is an  invalid  "errno"  value  for  the
     underlying platform. */
  return (cce_condition_t *) &cce_invalid_errno_condition;
}

/* end of file */
